language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer install --prefer-source --no-interaction --dev
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script: vendor/bin/phpunit
